### PR TITLE
Collected fixes

### PR DESCRIPTION
**Pull request by thp**
Here's a small collection of fixes I've collected from other repos, as listed here:
https://github.com/jagregory/abrash-black-book/network

Not sure if all of them are mergeable as-is, but would be good to get at least parts of this reviewed and merged (plus maybe do another "release" on GitHub, since version 1.0 is from Jan 19, 2014 and I've already seen issues while reading that turned out to have been fixed in the master branch).

### CODE REVIEW

**Comment by thp** [comment]
A snapshot epub build of this branch is available from here:
https://github.com/thp/abrash-black-book/releases/tag/2018-07-05

**Comment by thp** [comment]
Updated snapshot epub build of this branch is available from here:
https://github.com/thp/abrash-black-book/releases/tag/2018-12-03

**Comment by jagregory** [comment]
Ok, I can see now that this is a collection of some other Pull Requests. I'm going to review those independently.

**Comment by jagregory** [comment]
I've merged most of the open Pull Requests which make up this one, and have published a new version. If there's anything I've missed that this PR has, please rebase and let me know. Thanks

**Comment by thp** [comment]
Closing as per your last comment, thanks! :)

**Pull request closed without merging**
