### PR TITLE
feat: Chapter A

### PR DESCRIPTION
**Pull request by northern**
On the companion CD of this book there are included chapters A to K in PDF format, many of the conventional chapters in the book actually refer to these chapters from time to time. I'm not sure why, but they don't seem to have been released with the rest of the book when it was published online. I thought it might be worth while adding these chapters to this version of the book since they contain valuable information.

This is my attempt to add Chapter A. I have copied and pasted the contents of Chapter A to the `chapter-a.md` file, including the code sample (which requires a lot of fixing due to how PDF's are layed out), and I have added the chapter images as JPG's.

It probably needs a good bit of scrutiny but feedback is welcome.

PS: I have no idea how long it will take to get all chapters A to K done, so if this sort of contibution is welcome it will probably take a while before all chapters are added.

### CODE REVIEW

**Comment by joruib** [comment]
I'm sure I still have the CD that came with the book. If  you want any help in transcribing the appendixes, let me know and I'll start with the K one (backwards from you).

**Comment by northern** [comment]
@joruib That would be great. Thanks!

It also seems that someone has uploaded the disk image to archive.org. I guess that could be used for reference as well.

https://archive.org/details/blackbook_201910

**Comment by jagregory** [comment]
Looks great @northern! I assume these chapters should form some kind of appendices section at the end of the book?

For this to be included in the final output you'll need to modify the Makefile, there's a big ordered list of files at the top of it and you'll just need to insert the new chapter at the appropriate place. If you do that, we can preview it and see how it looks.

**Comment by northern** [comment]
@jagregory Great! I was wondering how the index was generated.

I have introduced an "Appendices" section under which the Chapter's A to K can live. I have added it after the "Afterword" (appendix-a.md) since that's where the printed book stops. Let me know if you agree with this or if you'd prefer to have it stuctured differently.

So, without having to dig through it, its structured like this:

6. Afterword
7. Appendices
   1. Chapter A – Paging Mr. VGA
       - More Colors in 16-Color Mode through VGA Color Paging
       - Breaking Code by Upgrading Compilers
       - Color Paging
       - How to Perform Color Paging
       - Obtaining the Color Paging State
       - An Example of Color Paging
       - Paging Invisible Pages
8. About this version

The generated HTML looks fine as well. Oh, I've added a `.gitignore` to make sure that the `out` directory isn't commited by accident.

Let me know what you think.

**Comment by joruib** [comment]
@jagregory I sent you an email last November but I don't know if it was the correct address, did you get it? It was about forking the repository to up load several chapters I translated into Spanish and eventually finishing the entire book (a titanical effort I'm afraid... my target are the VGA and Quake chapters).

**Comment by jagregory** [comment]
Hey @northern, as you can imagine I got a little distracted over the past couple of years... Do you still have the original PDFs for the other chapters?

**Comment by northern** [comment]
@jagregory Hey! No worries. The extra chapters are included on the CDROM that came with the book. You can find an image of the disk on Archive.org: https://archive.org/details/blackbook_201910

**Comment by jagregory** [comment]
Ah that's great, thanks! Looks like there's even the actual code for all the other chapters too, that could be very useful.

**Pull request merged**
